# Generated by Django 4.0.2 on 2022-02-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretary',
            name='pic',
            field=models.FileField(default='pofile.png', upload_to='profile'),
        ),
    ]
