# Generated by Django 4.0.2 on 2022-02-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_secretary_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(max_length=5)),
                ('image', models.FileField(blank=True, null=True, upload_to='house-image')),
            ],
        ),
    ]
