# Generated by Django 4.0.2 on 2022-02-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='room_no',
            field=models.IntegerField(),
        ),
    ]
