# Generated by Django 4.0.2 on 2022-02-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_house_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.FileField(default=1, upload_to='house-image'),
            preserve_default=False,
        ),
    ]
