# Generated by Django 4.0.2 on 2022-02-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='doc',
            field=models.CharField(choices=[('pan', 'PAN Card '), ('aadhar', 'AAdhar Card')], max_length=20),
        ),
    ]
