# Generated by Django 4.0.2 on 2022-03-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Gallery-image'),
        ),
    ]
