name: WorkFlow
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "E121,E123,E126,E128,E303,E501,F401,F403,F405,W291,W391,W503,W504"
          exclude: ".venv,__pycache__,migrations"

      - name: Search for while keyword
        id: while_keyword
        run: |
          if grep -r --include=\*.py --include=\*.js --include=\*.html -v \
             -e '^\s*#' -e '^\s*//.*$' -e '"' -e "'" -e '^\s*\*' . |
            perl -0777 -pe 's/<!--.*?-->//gs' |
            perl -0777 -pe 's/\/\*.*?\*\///gs' |
            perl -0777 -pe 's/\"""\.*?\"""\//gs' |
            perl -0777 -pe "s/\'''\.*?\'''\//gs" |
            grep -E '\bwhile\b'; then
              echo "'while' keyword found!" >> error.log
          else
              echo "No 'while' keyword found."
          fi

      - name: Check for errors
        run: |
          if [ -f error.log ]; then
            cat error.log
            exit 1
          else
            echo "No issues found."
          fi